### ISSUE TITLE
[meta] e2e deployments + project polish

### ISSUE THREAD

**Issue by sgoings** [kubernetes/helm#474]
Based on the conversations in the 3/30/16 retro:

### Big Features
- [x] Get deployments working from client to server (https://github.com/kubernetes/helm/issues/471)
- [ ] Go template expansion for charts (https://github.com/kubernetes/helm/issues/401)
- [ ] Produce a first pass e2e testing of deployments (@adamreese to create issue)
- [x] `helm deployment describe`
- [x] gsutil guide for uploading charts (https://github.com/kubernetes/helm/issues/476)

### Project Polish Items
- [x] Helm server install (install dm into “helm” namespace)
- [ ] Readme needs a bit of rework
- [x] More user friendly errors
- [x] Helm server side images stored in helm-k8s-prod
- [ ] Chart format has changed a bit (add modifications to chart.md)  (https://github.com/kubernetes/helm/issues/554)
- [x] Add a simple getting started example(s) (https://github.com/kubernetes/helm/issues/475)
