### ISSUE TITLE
[meta] Week of April 4 2016

### ISSUE THREAD

**Issue by jackgr** [kubernetes/helm#557]
See the IdeaBoardz result [here](http://www.ideaboardz.com/retros/export/2459068/Helm%20Retro.pdf).

Action item checklist:
- [ ] Migrate charts to kubernetes/charts
- [ ] Testing
- [ ] Pluggable templating engines
- [ ] Review outstanding design decisions

**Comment by sgoings** [comment]
All but one of these issues are all coordinated in the MVP milestone: https://github.com/kubernetes/helm/issues?q=is%3Aopen+is%3Aissue+milestone%3A%22Minimum+Viable+Product%22

Migrate charts: (already done)
Testing: #352 
Review outstanding design decisions: #520

The pluggable templating engine seems like a feature not really meant for an MVP, so I'd rather see that work happen after we demo our MVP to the SIG config.

Can we close this in favor of marking Testing and the design review (already scheduled) as P0?

**Comment by jackgr** [comment]
As discussed in the planning session yesterday, pluggable templating engine is required to support Go templates, which is part of MVP.

Re: closing this in favor of using the MVP milestone, do we have a complete list of work items remaining for MVP and an estimate of time to delivery? If not, or if the estimate is > 1 week, then I'd like to keep this issue open or create an actual milestone (preferable) for this week's work.

**Comment by sparkprime** [comment]
The initial charts migration PR is not in yet.  And the full migration (i.e. getting charts that actaully work) is dependent on "pluggable templating engines" which is really not a great name for the feature of "supporting more than just expandybird".

**Comment by sparkprime** [comment]
@jackgr Can I suggest that we hardcode go templates as well as expandybird unless you can get the DNS-based approach working today?  Just use hard-coded names that are valid k8s service names and we can change it under the hood later.

**Comment by jackgr** [comment]
I'll get DNS working today. Already half done.

**Comment by sgoings** [comment]
@jackgr I'd love to see us ship MVP before we demo Helm to SIG config. Why don't we just focus on knocking out the things left in the MVP milestone?

Do we want to set a date for when MVP will arrive?
