### ISSUE TITLE
[META] Commands to be implemented for MVP

### ISSUE THREAD

**Issue by technosophos** [kubernetes/helm#646]
- [x] `helm init`
- [x] `helm create PATH`
- [x] `helm package [PATH]`
- [x] `helm install CHARTREF` (where CHARTREF is a path or HTTP(S) URL)
- [x] `helm status RELEASE` (where RELEASE is a release name)
- [x] `helm get RELEASE`
- [x] `helm list [EXPRESSION]` (list releases)
- [x] `helm delete RELEASE`
- [x] `helm fetch URL`
- [x] `helm repo add REPO URL`
- [x] `helm repo list`
- [x] `helm repo rm REPO`
- [x] `helm update`
- [x] `helm search EXPRESSION`

Deferred to post-MVP:

- `helm upgrade RELEASE`
- `helm lint`
